### PR TITLE
[WIP] Calibration update

### PR DESCRIPTION
**Pull request by rete**
BEGINRELEASENOTES
- new calibration and software compensation for ILD_l4_v02
     - Updated calibration constants in main Marlin file: bbudsc_3evt_stdreco_dd4hep.xml
     - Updated software compensation parameters in all Pandora settings files
     - Added calibration report files for easy comparison with incoming re-calibrations

ENDRELEASENOTES

### CODE REVIEW

**Comment by rete** [comment]
This work in progress. I just provided the first bullet point...

**Comment by rete** [comment]
Crucial remark : The calibration update is for the ILD_l4_v02 model here. I will do, at some point, a PR for updating calibration contants for the ILD_s4_v02 model.
How should we proceed ? There is only one Marlin steering file for the moment ...

**Comment by rete** [comment]
I updated the calibration constants for the ILD model ILD_l4_v02 and software compensation weights for this model also. Ready for merging on my side

**Comment by gaede** [comment]
@rete I have updated the release notes to document that this deals w/ ILD_l4_v02 only.
There is a conflict with your PR that you need to resolve locally with rebasing before this can be merged...

**Comment by rete** [comment]
There is no conflict on my local version, even after a pull. Am I missing something ?

**Pull request merged**
