### PR TITLE
[WIP] Switch on features

### PR DESCRIPTION
**Pull request by rete**
BEGINRELEASENOTES
- PandoraPFA settings:
   - Switch on usage of dd4hep B field
   - Correct missing relation calo hit collections
- BeamCalReco settings
   - Switch on BeamCalReco by default
- Updated documentation

ENDRELEASENOTES

### CODE REVIEW

**Comment by gaede** [comment]
@rete are you finished with this  ( still has WIP) ?

**Comment by rete** [comment]
Yes I'm done. But we should wait for Travis, in this case this is important.

**Comment by rete** [comment]
@gaede Should I update the README and documentation to point on a new release v01-19-06 before merging this ?

**Comment by gaede** [comment]
Yes, but please let Travis finish once - then we don't have to wait again with text changes only ...

**Comment by rete** [comment]
Wait again for Travis to finish, I have made other important changes ... unfortunately ...

**Pull request merged**
