### PR TITLE
change to default parameters for field stepping

### PR DESCRIPTION
**Pull request by gaede**
BEGINRELEASENOTES
- change to default parameters for field stepping in Geant4
   - test if this works for ILD and improves simulation speed (see: #48)

ENDRELEASENOTES

### CODE REVIEW

**Comment by rete** [comment]
By running our 3 events test on the NAF, I see the following : 

- With the old config (v01-19-05-p01) : `Execution Time: 218.60 s (User), 1.02 s (System)`
- With the proposed settings in this PR : `Execution Time: 188.22 s (User), 2.15 s (System)`

thus an improvement of ~14% on execution time.

One have to see the potential impact on the precision of the tracking in the reconstruction.
@shaojunlu Any guess on how much the tracking performance could be the impacted with these new settings ?

**Comment by petricm** [comment]
@rete for your claim of 14% did you subtract the startup time of DD4hep (geometry creation) since if you only generate 3 events the startup time represents a substantial fraction of the total execution time?

**Comment by rete** [comment]
No sorry. By taking this into account I roughly get 60 seconds of initialization before processing the first event. The improvement finally goes to almost 20%.

**Comment by rete** [comment]
If we are confident enough from the Geant4 side with these new settings, we can merge this PR.

**Pull request merged**
