### PR TITLE
[WIP] Updates on sdhcal reco

### PR DESCRIPTION
**Pull request by rete**
BEGINRELEASENOTES
- Updated sdhcal Pandora settings file for SDHCAL reconstruction
- Updated sdhcal Marlin steering file for SDHCAL reconstruction

ENDRELEASENOTES

### CODE REVIEW

**Comment by rete** [comment]
@libo929 I updated the reconstruction files for sdhcal. Still, the digitizer shows runtime error : 

```shell
 ***********************************************
 A runtime error occured - (uncaught exception):
      lcio::Exception:  BitFieldValue: unknown name: y
 Marlin will have to be terminated, sorry.
 ***********************************************
```

Can you suggest a fix for that ?

**Comment by libo929** [comment]
@rete We noticed this issue. Maybe people are also trying to fix it in the lcgeo code where "z" is used. Anyway, we fixed the digitizer now. BTW, the cell size from dd4hep is currently for AHCAL by default, so one of our solution is to hard code the cell size.

**Comment by rete** [comment]
@libo929 To correctly use the current lcgeo implementation for sdhcal studies you nee to modify a parameter in the detector geometry itself : 

[https://github.com/iLCSoft/lcgeo/blob/master/ILD/compact/ILD_common_v02/hcal_defs.xml#L76](https://github.com/iLCSoft/lcgeo/blob/master/ILD/compact/ILD_common_v02/hcal_defs.xml#L76)

The two value="1" have to be changed to value="3" while running the reconstruction. This will change the segmentation to the correct one : 
[https://github.com/iLCSoft/lcgeo/blob/master/ILD/compact/ILD_common_v02/SHcalSc04_Barrel_v04.xml#L38](https://github.com/iLCSoft/lcgeo/blob/master/ILD/compact/ILD_common_v02/SHcalSc04_Barrel_v04.xml#L38)

By doing so, you can reconstruct events with SDHCAL. Can you test these new configuration files after setting the correct segmentation for SDHCAL ?

**Comment by libo929** [comment]
@rete It can work, we have tested it.

**Pull request merged**
