### PR TITLE
Activate TPC dEdX smearing

### PR DESCRIPTION
**Pull request by rete**
BEGINRELEASENOTES
- Compute_dEdX processor: 
   - Copy default dEdX processor parameters in the XML file. 
   - Smearing option switched to on.

ENDRELEASENOTES

Tested with our 3 events test : no error raised

### CODE REVIEW

**Comment by rete** [comment]
Pinging @MasakazuKurata for review

**Comment by rete** [comment]
Please @MasakazuKurata can you confirm that these parameters are valid ?

**Comment by MasakazuKurata** [comment]
All the parameters on the steering file are OK.
But Please wait for activationg smearing of dE/dx because I found a bug.
I will fix and add parameters on new steering files

**Comment by rete** [comment]
@MasakazuKurata After merging iLCSoft/MarlinReco#42 we can now deal with these parameters. Can you now check this in detail ? Should I merge the proposed changes here as they are, or do we need more updates to cope with your recent changes ?

**Comment by MasakazuKurata** [comment]
Dear RemiI have checked parameters for dEdx and PID and turned on dEdx smearing.
Thanks
Masakazu Kurata



----- Original Message -----

**Comment by rete** [comment]
Superseded by #60 and #63

**Pull request closed without merging**
