### PR TITLE
[WIP] SDHcal config updates + MC production updates

### PR DESCRIPTION
**Pull request by rete**
BEGINRELEASENOTES
- Updated SDHcal reconstruction config
  - Updated digitizer config to match the new version. See PR  [iLCSoft/MarlinReco/30](https://github.com/iLCSoft/MarlinReco/pull/30)
  - Updated SDHcal calibration constants
  - Moved Pandora settings file constant definition to Calibration directory files, as it is calorimeter dependant 
- Removed GearXMLFile parameter as it is not needed anymore
- Added Documentation for : 
  - DST content
  - how to run bg overlay
  - ILD MC production settings
- Set ILD_l5_o1_v02 as default model in steering files and documentation
ENDRELEASENOTES

### CODE REVIEW

**Comment by rete** [comment]
This is WIP. Needs to be tested before merging  !

**Comment by rete** [comment]
Works on my side with pre-release v01-15-05-pre05 on afs. Even with the full background overlay (4 gg + pair bg) !
Waiting for SDHCAL team review ...

**Comment by gaede** [comment]
@rete can you please
- fix the missing newlines at the end of the files
- include https://github.com/iLCSoft/ILDConfig/pull/34, i.e. remove the Gear file from the main steering file
- generate all the steering files in ./ProductionSteeringFiles, so that we can test these as well

**Comment by rete** [comment]
All done. Let me update the release notes accordingly

**Comment by rete** [comment]
@shaojunlu Is everthing else correct for the viewers settings ?

**Comment by shaojunlu** [comment]
@rete 
There is "<processor name="MyInitializeDD4hep"/>" in both https://github.com/rete/ILDConfig/blob/sdhcal-config/StandardConfig/production/MarlinStdRecoViewer.xml and https://github.com/rete/ILDConfig/blob/sdhcal-config/StandardConfig/production/MarlinStdRecoViewerDST.xml
So both could only read detector geometry from "GearXMLFile".

https://github.com/rete/ILDConfig/blob/sdhcal-config/StandardConfig/production/README.md
Marlin MarlinStdRecoViewer.xml --global.GearXMLFile=ILD_l5_v02.xml
Marlin MarlinStdRecoViewerDST.xml --global.GearXMLFile=ILD_l5_v02.xml

ced2go -s 1 -d $lcgeo_DIR/ILD/compact/ILD_l5_o1_v02/ILD_l4_o5_v02.xml StandardReco_REC.slcio
ced2go works without gear.
But with "-s 1" option, it shows strange TPC surface.
Frank is look at this issue. I do not think that it came from here.

**Pull request merged**
